// Code generated by Wire. DO NOT EDIT.
//
// Hand-maintained to match wire.go until `go generate` is wired in CI.

//go:build !wireinject

package main

import (
	"thuanle/cse-mark/internal/configs"
	"thuanle/cse-mark/internal/delivery/tele"
	"thuanle/cse-mark/internal/delivery/tele/handlers"
	"thuanle/cse-mark/internal/delivery/tele/middlewares"
	"thuanle/cse-mark/internal/delivery/tele/views"
	"thuanle/cse-mark/internal/domain/course"
	"thuanle/cse-mark/internal/infra/email"
	"thuanle/cse-mark/internal/infra/http"
	"thuanle/cse-mark/internal/infra/mongo"
	"thuanle/cse-mark/internal/usecases/iam"
	"thuanle/cse-mark/internal/usecases/identity"
	"thuanle/cse-mark/internal/usecases/markimport"
)

// App is the resolved dependency graph.
type App struct {
	Config      *configs.Config
	MongoClient *mongo.Client
	TeleService *tele.Service
}

func InitializeApp() (*App, error) {
	config := configs.LoadConfig()
	client, err := mongo.NewClient(config)
	if err != nil {
		return nil, err
	}
	rules := course.NewRules(config)
	repository := mongo.NewMarkRepo(client, config)
	studentRepo := mongo.NewStudentRepo(client, config)
	bindingRepo := mongo.NewBindingRepo(client, config)
	verificationRepo := mongo.NewVerificationRepo(client, config)
	sender := ProvideSender(config)
	ident := identity.NewService(studentRepo, verificationRepo, bindingRepo, sender, config)
	guest := ProvideGuestHandler(rules, repository, ident)
	courseRepository := mongo.NewCourseRepo(client, config)
	teacherRenderer := views.NewTeacherRenderer(rules)
	userRepository := mongo.NewUserRepo(client, config)
	authzService := iam.NewAuthzService(courseRepository, userRepository)
	downloaderRepository := http.NewSimpleDownloader(config)
	service := markimport.NewService(downloaderRepository, courseRepository, repository)
	teacher := handlers.NewTeacherHandler(courseRepository, rules, teacherRenderer, authzService, repository, service)
	admin := handlers.NewAdminHandler(userRepository)
	teacherOnly := middlewares.NewTeacherOnly(authzService)
	bind := handlers.NewBindHandler(ident)
	teleService, err := tele.NewService(config, guest, teacher, admin, bind, teacherOnly)
	if err != nil {
		return nil, err
	}

	// keep email import referenced (LogSender lives there)
	_ = email.NewLogSender

	app := &App{
		Config:      config,
		MongoClient: client,
		TeleService: teleService,
	}
	return app, nil
}
