// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"thuanle/cse-mark/internal/configs"
	"thuanle/cse-mark/internal/delivery/tele"
	"thuanle/cse-mark/internal/delivery/tele/handlers"
	"thuanle/cse-mark/internal/delivery/tele/middlewares"
	"thuanle/cse-mark/internal/delivery/tele/views"
	"thuanle/cse-mark/internal/domain/course"
	"thuanle/cse-mark/internal/infra/http"
	"thuanle/cse-mark/internal/infra/mongo"
	"thuanle/cse-mark/internal/usecases/iam"
	"thuanle/cse-mark/internal/usecases/identity"
	"thuanle/cse-mark/internal/usecases/markimport"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	config := configs.LoadConfig()
	client, err := mongo.NewClient(config)
	if err != nil {
		return nil, err
	}
	rules := course.NewRules(config)
	repository := mongo.NewMarkRepo(client, config)
	courseRepository := mongo.NewCourseRepo(client, config)
	studentRepository := mongo.NewStudentRepo(client, config)
	verificationRepository := mongo.NewVerificationRepo(client, config)
	bindingRepository := mongo.NewBindingRepo(client, config)
	sender := ProvideSender(config)
	service := identity.NewService(studentRepository, verificationRepository, bindingRepository, sender, config)
	guest := ProvideGuestHandler(rules, repository, courseRepository, service)
	teacherRenderer := views.NewTeacherRenderer(rules)
	userRepository := mongo.NewUserRepo(client, config)
	authzService := iam.NewAuthzService(courseRepository, userRepository)
	simpleDownloader := http.NewSimpleDownloader(config)
	string2 := configs.ProvideGvProxyToken(config)
	markimportService := markimport.NewService(simpleDownloader, courseRepository, repository, string2)
	teacher := handlers.NewTeacherHandler(courseRepository, rules, teacherRenderer, authzService, repository, markimportService)
	admin := handlers.NewAdminHandler(userRepository)
	bind := ProvideBindHandler(service)
	teacherOnly := middlewares.NewTeacherOnly(authzService)
	teleService, err := tele.NewService(config, guest, teacher, admin, bind, teacherOnly)
	if err != nil {
		return nil, err
	}
	app := &App{
		Config:      config,
		MongoClient: client,
		TeleService: teleService,
	}
	return app, nil
}

// wire.go:

type App struct {
	Config      *configs.Config
	MongoClient *mongo.Client
	TeleService *tele.Service
}
