# BUILD
FROM golang:1.23-alpine AS build

WORKDIR /app

COPY . .

RUN go mod tidy

WORKDIR /app/cmd/api
RUN go build -o api

# RUN IMAGE
FROM alpine
WORKDIR /app
COPY --from=build /app/cmd/api/api .

CMD ["./api"]