// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"thuanle/cse-mark/internal/configs"
	http2 "thuanle/cse-mark/internal/delivery/http"
	"thuanle/cse-mark/internal/delivery/http/handlers"
	"thuanle/cse-mark/internal/infra/http"
	"thuanle/cse-mark/internal/infra/mongo"
	"thuanle/cse-mark/internal/usecases/markimport"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	config := configs.LoadConfig()
	client, err := mongo.NewClient(config)
	if err != nil {
		return nil, err
	}
	repository := mongo.NewMarkRepo(client, config)
	guestHandler := handlers.NewGuestHandler(repository, config)
	downloaderRepository := http.NewSimpleDownloader(config)
	courseRepository := mongo.NewCourseRepo(client, config)
	service := markimport.NewService(downloaderRepository, courseRepository, repository)
	teacherHandler := handlers.NewTeacherHandler(service)
	httpService := http2.NewHttpService(guestHandler, teacherHandler)
	app := &App{
		Config:      config,
		MongoClient: client,
		HttpService: httpService,
	}
	return app, nil
}

// wire.go:

type App struct {
	Config      *configs.Config
	MongoClient *mongo.Client
	HttpService *http2.Service
}
