// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"thuanle/cse-mark/internal/configs"
	"thuanle/cse-mark/internal/delivery/api"
	"thuanle/cse-mark/internal/delivery/api/handlers"
	"thuanle/cse-mark/internal/delivery/api/middlewares"
	"thuanle/cse-mark/internal/infra/mongo"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	config := configs.LoadConfig()
	client, err := mongo.NewClient(config)
	if err != nil {
		return nil, err
	}
	auth := middlewares.NewAuthMiddleware(config)
	repository := mongo.NewMarkRepo(client, config)
	marks := handlers.NewMarksHandler(repository)
	service := api.NewApiService(auth, marks, config)
	app := &App{
		Config:      config,
		MongoClient: client,
		ApiService:  service,
	}
	return app, nil
}

// wire.go:

type App struct {
	Config      *configs.Config
	MongoClient *mongo.Client
	ApiService  *api.Service
}
