package binding

// Model links a platform chat account to an MSSV. Platform is "telegram" or
// "discord". The 1:1:1 constraint (one MSSV <-> at most one chat id per
// platform) is enforced by unique indexes on (platform, platform_user_id) and
// (platform, mssv). The _id is auto-generated by MongoDB.
type Model struct {
	Platform       string `json:"platform"         bson:"platform"`
	PlatformUserID string `json:"platform_user_id" bson:"platform_user_id"`
	MSSV           string `json:"mssv"             bson:"mssv"`
	Verified       bool   `json:"verified"         bson:"verified"`
	BoundAt        int64  `json:"bound_at"         bson:"bound_at"`
}
